// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Bookmark struct {
	Login     string
	Repo      string
	CreatedAt string
	Note      *string
	NoteTerms *string
}

type History struct {
	Login         string
	Kind          string
	Repo          string
	Number        int64
	Title         *string
	FirstViewedAt string
	LastViewedAt  string
	ViewCount     int64
}

type QueueItem struct {
	Login      string
	Repo       string
	Number     int64
	Title      *string
	AddedAt    string
	LastSeenAt *string
	Note       *string
	NoteTerms  *string
	TitleTerms *string
}

type SearchIndex struct {
	Repo  string
	Title string
	Note  string
}

type SearchKey struct {
	ID     int64
	Kind   string
	Login  string
	Repo   string
	Number int64
}

type User struct {
	Login                string
	GithubID             int64
	Name                 *string
	AvatarUrl            *string
	TokenVersion         int64
	CreatedAt            string
	LastLoginAt          *string
	HistoryRetentionDays int64
	HistoryPaused        int64
}
