// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Bookmark struct {
	Login     string
	Repo      string
	CreatedAt string
}

type History struct {
	Login         string
	Kind          string
	Repo          string
	Number        int64
	Title         *string
	FirstViewedAt string
	LastViewedAt  string
	ViewCount     int64
}

type QueueItem struct {
	Login      string
	Repo       string
	Number     int64
	Title      *string
	AddedAt    string
	LastSeenAt *string
}

type User struct {
	Login                string
	GithubID             int64
	Name                 *string
	AvatarUrl            *string
	TokenVersion         int64
	CreatedAt            string
	LastLoginAt          *string
	HistoryRetentionDays int64
	HistoryPaused        int64
}
