// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const bumpTokenVersion = `-- name: BumpTokenVersion :exec
UPDATE users SET token_version = token_version + 1 WHERE github_id = ?
`

// Revokes every session issued so far (they carry the old version).
func (q *Queries) BumpTokenVersion(ctx context.Context, githubID int64) error {
	_, err := q.db.ExecContext(ctx, bumpTokenVersion, githubID)
	return err
}

const countBookmarks = `-- name: CountBookmarks :one
SELECT COUNT(*) FROM bookmarks WHERE login = ?
`

func (q *Queries) CountBookmarks(ctx context.Context, login string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBookmarks, login)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQueueItems = `-- name: CountQueueItems :one
SELECT COUNT(*) FROM queue_items WHERE login = ?
`

func (q *Queries) CountQueueItems(ctx context.Context, login string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQueueItems, login)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBookmark = `-- name: DeleteBookmark :exec
DELETE FROM bookmarks WHERE login = ? AND repo = ?
`

type DeleteBookmarkParams struct {
	Login string
	Repo  string
}

func (q *Queries) DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) error {
	_, err := q.db.ExecContext(ctx, deleteBookmark, arg.Login, arg.Repo)
	return err
}

const deleteQueueItem = `-- name: DeleteQueueItem :exec
DELETE FROM queue_items WHERE login = ? AND repo = ? AND number = ?
`

type DeleteQueueItemParams struct {
	Login  string
	Repo   string
	Number int64
}

func (q *Queries) DeleteQueueItem(ctx context.Context, arg DeleteQueueItemParams) error {
	_, err := q.db.ExecContext(ctx, deleteQueueItem, arg.Login, arg.Repo, arg.Number)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE github_id = ?
`

// Deletes the account; ON DELETE CASCADE removes its bookmarks and queue.
func (q *Queries) DeleteUser(ctx context.Context, githubID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, githubID)
	return err
}

const ensureQueueItem = `-- name: EnsureQueueItem :one
INSERT INTO queue_items (login, repo, number) VALUES (?, ?, ?)
ON CONFLICT (login, repo, number) DO UPDATE SET repo = excluded.repo
RETURNING login, repo, number, title, added_at, last_seen_at
`

type EnsureQueueItemParams struct {
	Login  string
	Repo   string
	Number int64
}

// Used when the request has no title: a queued item keeps the one it has.
func (q *Queries) EnsureQueueItem(ctx context.Context, arg EnsureQueueItemParams) (QueueItem, error) {
	row := q.db.QueryRowContext(ctx, ensureQueueItem, arg.Login, arg.Repo, arg.Number)
	var i QueueItem
	err := row.Scan(
		&i.Login,
		&i.Repo,
		&i.Number,
		&i.Title,
		&i.AddedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getBookmark = `-- name: GetBookmark :one
SELECT login, repo, created_at FROM bookmarks WHERE login = ? AND repo = ?
`

type GetBookmarkParams struct {
	Login string
	Repo  string
}

func (q *Queries) GetBookmark(ctx context.Context, arg GetBookmarkParams) (Bookmark, error) {
	row := q.db.QueryRowContext(ctx, getBookmark, arg.Login, arg.Repo)
	var i Bookmark
	err := row.Scan(&i.Login, &i.Repo, &i.CreatedAt)
	return i, err
}

const getQueueItem = `-- name: GetQueueItem :one
SELECT login, repo, number, title, added_at, last_seen_at FROM queue_items WHERE login = ? AND repo = ? AND number = ?
`

type GetQueueItemParams struct {
	Login  string
	Repo   string
	Number int64
}

func (q *Queries) GetQueueItem(ctx context.Context, arg GetQueueItemParams) (QueueItem, error) {
	row := q.db.QueryRowContext(ctx, getQueueItem, arg.Login, arg.Repo, arg.Number)
	var i QueueItem
	err := row.Scan(
		&i.Login,
		&i.Repo,
		&i.Number,
		&i.Title,
		&i.AddedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserByGithubID = `-- name: GetUserByGithubID :one


SELECT login, github_id, name, avatar_url, token_version, created_at, last_login_at FROM users WHERE github_id = ?
`

// Queries compiled by sqlc (see sqlc.yaml). Engine: SQLite (Cloudflare D1).
// Timestamps are RFC 3339 UTC strings, the same format as the column defaults.
// ---------- users ----------
func (q *Queries) GetUserByGithubID(ctx context.Context, githubID int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByGithubID, githubID)
	var i User
	err := row.Scan(
		&i.Login,
		&i.GithubID,
		&i.Name,
		&i.AvatarUrl,
		&i.TokenVersion,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT login, github_id, name, avatar_url, token_version, created_at, last_login_at FROM users WHERE login = ?
`

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByLogin, login)
	var i User
	err := row.Scan(
		&i.Login,
		&i.GithubID,
		&i.Name,
		&i.AvatarUrl,
		&i.TokenVersion,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (login, github_id, token_version) VALUES (?, ?, ?)
`

type InsertUserParams struct {
	Login        string
	GithubID     int64
	TokenVersion int64
}

// New accounts start at a random token version (see auth.NewTokenVersion).
func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser, arg.Login, arg.GithubID, arg.TokenVersion)
	return err
}

const listBookmarks = `-- name: ListBookmarks :many

SELECT login, repo, created_at FROM bookmarks WHERE login = ? ORDER BY created_at DESC, rowid DESC
`

// ---------- bookmarks ----------
// rowid breaks ties between rows created in the same second.
func (q *Queries) ListBookmarks(ctx context.Context, login string) ([]Bookmark, error) {
	rows, err := q.db.QueryContext(ctx, listBookmarks, login)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bookmark{}
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(&i.Login, &i.Repo, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueueItems = `-- name: ListQueueItems :many

SELECT login, repo, number, title, added_at, last_seen_at FROM queue_items WHERE login = ? ORDER BY added_at DESC, rowid DESC
`

// ---------- review queue ----------
func (q *Queries) ListQueueItems(ctx context.Context, login string) ([]QueueItem, error) {
	rows, err := q.db.QueryContext(ctx, listQueueItems, login)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueueItem{}
	for rows.Next() {
		var i QueueItem
		if err := rows.Scan(
			&i.Login,
			&i.Repo,
			&i.Number,
			&i.Title,
			&i.AddedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markQueueItemSeen = `-- name: MarkQueueItemSeen :one
UPDATE queue_items
SET last_seen_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE login = ? AND repo = ? AND number = ?
RETURNING login, repo, number, title, added_at, last_seen_at
`

type MarkQueueItemSeenParams struct {
	Login  string
	Repo   string
	Number int64
}

func (q *Queries) MarkQueueItemSeen(ctx context.Context, arg MarkQueueItemSeenParams) (QueueItem, error) {
	row := q.db.QueryRowContext(ctx, markQueueItemSeen, arg.Login, arg.Repo, arg.Number)
	var i QueueItem
	err := row.Scan(
		&i.Login,
		&i.Repo,
		&i.Number,
		&i.Title,
		&i.AddedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const renameUser = `-- name: RenameUser :exec
UPDATE users SET login = ? WHERE github_id = ?
`

type RenameUserParams struct {
	Login    string
	GithubID int64
}

// Moves the account (and, through ON UPDATE CASCADE, its bookmarks and queue)
// to another handle.
func (q *Queries) RenameUser(ctx context.Context, arg RenameUserParams) error {
	_, err := q.db.ExecContext(ctx, renameUser, arg.Login, arg.GithubID)
	return err
}

const touchUserLogin = `-- name: TouchUserLogin :one
UPDATE users
SET name = ?,
    avatar_url = ?,
    last_login_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE github_id = ?
RETURNING login, github_id, name, avatar_url, token_version, created_at, last_login_at
`

type TouchUserLoginParams struct {
	Name      *string
	AvatarUrl *string
	GithubID  int64
}

func (q *Queries) TouchUserLogin(ctx context.Context, arg TouchUserLoginParams) (User, error) {
	row := q.db.QueryRowContext(ctx, touchUserLogin, arg.Name, arg.AvatarUrl, arg.GithubID)
	var i User
	err := row.Scan(
		&i.Login,
		&i.GithubID,
		&i.Name,
		&i.AvatarUrl,
		&i.TokenVersion,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const upsertBookmark = `-- name: UpsertBookmark :one
INSERT INTO bookmarks (login, repo) VALUES (?, ?)
ON CONFLICT (login, repo) DO UPDATE SET repo = excluded.repo
RETURNING login, repo, created_at
`

type UpsertBookmarkParams struct {
	Login string
	Repo  string
}

// An existing row keeps its created_at; only the spelling of the repo follows the request.
func (q *Queries) UpsertBookmark(ctx context.Context, arg UpsertBookmarkParams) (Bookmark, error) {
	row := q.db.QueryRowContext(ctx, upsertBookmark, arg.Login, arg.Repo)
	var i Bookmark
	err := row.Scan(&i.Login, &i.Repo, &i.CreatedAt)
	return i, err
}

const upsertQueueItem = `-- name: UpsertQueueItem :one
INSERT INTO queue_items (login, repo, number, title) VALUES (?, ?, ?, ?)
ON CONFLICT (login, repo, number) DO UPDATE SET repo = excluded.repo, title = excluded.title
RETURNING login, repo, number, title, added_at, last_seen_at
`

type UpsertQueueItemParams struct {
	Login  string
	Repo   string
	Number int64
	Title  *string
}

// Used when the request carries a title.
func (q *Queries) UpsertQueueItem(ctx context.Context, arg UpsertQueueItemParams) (QueueItem, error) {
	row := q.db.QueryRowContext(ctx, upsertQueueItem,
		arg.Login,
		arg.Repo,
		arg.Number,
		arg.Title,
	)
	var i QueueItem
	err := row.Scan(
		&i.Login,
		&i.Repo,
		&i.Number,
		&i.Title,
		&i.AddedAt,
		&i.LastSeenAt,
	)
	return i, err
}
