// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const bumpTokenVersion = `-- name: BumpTokenVersion :exec
UPDATE users SET token_version = token_version + 1 WHERE github_id = ?
`

// Revokes every session issued so far (they carry the old version).
func (q *Queries) BumpTokenVersion(ctx context.Context, githubID int64) error {
	_, err := q.db.ExecContext(ctx, bumpTokenVersion, githubID)
	return err
}

const clearHistory = `-- name: ClearHistory :exec
DELETE FROM history WHERE login = ?
`

func (q *Queries) ClearHistory(ctx context.Context, login string) error {
	_, err := q.db.ExecContext(ctx, clearHistory, login)
	return err
}

const countBookmarks = `-- name: CountBookmarks :one
SELECT COUNT(*) FROM bookmarks WHERE login = ?
`

func (q *Queries) CountBookmarks(ctx context.Context, login string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBookmarks, login)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQueueItems = `-- name: CountQueueItems :one
SELECT COUNT(*) FROM queue_items WHERE login = ?
`

func (q *Queries) CountQueueItems(ctx context.Context, login string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQueueItems, login)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBookmark = `-- name: DeleteBookmark :exec
DELETE FROM bookmarks WHERE login = ? AND repo = ?
`

type DeleteBookmarkParams struct {
	Login string
	Repo  string
}

func (q *Queries) DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) error {
	_, err := q.db.ExecContext(ctx, deleteBookmark, arg.Login, arg.Repo)
	return err
}

const deleteHistoryItem = `-- name: DeleteHistoryItem :exec
DELETE FROM history WHERE login = ? AND kind = ? AND repo = ? AND number = ?
`

type DeleteHistoryItemParams struct {
	Login  string
	Kind   string
	Repo   string
	Number int64
}

func (q *Queries) DeleteHistoryItem(ctx context.Context, arg DeleteHistoryItemParams) error {
	_, err := q.db.ExecContext(ctx, deleteHistoryItem,
		arg.Login,
		arg.Kind,
		arg.Repo,
		arg.Number,
	)
	return err
}

const deleteQueueItem = `-- name: DeleteQueueItem :exec
DELETE FROM queue_items WHERE login = ? AND repo = ? AND number = ?
`

type DeleteQueueItemParams struct {
	Login  string
	Repo   string
	Number int64
}

func (q *Queries) DeleteQueueItem(ctx context.Context, arg DeleteQueueItemParams) error {
	_, err := q.db.ExecContext(ctx, deleteQueueItem, arg.Login, arg.Repo, arg.Number)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE github_id = ?
`

// Deletes the account; ON DELETE CASCADE removes its bookmarks, queue and history.
func (q *Queries) DeleteUser(ctx context.Context, githubID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, githubID)
	return err
}

const getBookmark = `-- name: GetBookmark :one
SELECT login, repo, created_at, note, note_terms FROM bookmarks WHERE login = ? AND repo = ?
`

type GetBookmarkParams struct {
	Login string
	Repo  string
}

func (q *Queries) GetBookmark(ctx context.Context, arg GetBookmarkParams) (Bookmark, error) {
	row := q.db.QueryRowContext(ctx, getBookmark, arg.Login, arg.Repo)
	var i Bookmark
	err := row.Scan(
		&i.Login,
		&i.Repo,
		&i.CreatedAt,
		&i.Note,
		&i.NoteTerms,
	)
	return i, err
}

const getQueueItem = `-- name: GetQueueItem :one
SELECT login, repo, number, title, added_at, last_seen_at, note, note_terms, title_terms FROM queue_items WHERE login = ? AND repo = ? AND number = ?
`

type GetQueueItemParams struct {
	Login  string
	Repo   string
	Number int64
}

func (q *Queries) GetQueueItem(ctx context.Context, arg GetQueueItemParams) (QueueItem, error) {
	row := q.db.QueryRowContext(ctx, getQueueItem, arg.Login, arg.Repo, arg.Number)
	var i QueueItem
	err := row.Scan(
		&i.Login,
		&i.Repo,
		&i.Number,
		&i.Title,
		&i.AddedAt,
		&i.LastSeenAt,
		&i.Note,
		&i.NoteTerms,
		&i.TitleTerms,
	)
	return i, err
}

const getUserByGithubID = `-- name: GetUserByGithubID :one


SELECT login, github_id, name, avatar_url, token_version, created_at, last_login_at, history_retention_days, history_paused FROM users WHERE github_id = ?
`

// Queries compiled by sqlc (see sqlc.yaml). Engine: SQLite (Cloudflare D1).
// Timestamps are RFC 3339 UTC strings, the same format as the column defaults.
// ---------- users ----------
func (q *Queries) GetUserByGithubID(ctx context.Context, githubID int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByGithubID, githubID)
	var i User
	err := row.Scan(
		&i.Login,
		&i.GithubID,
		&i.Name,
		&i.AvatarUrl,
		&i.TokenVersion,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.HistoryRetentionDays,
		&i.HistoryPaused,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT login, github_id, name, avatar_url, token_version, created_at, last_login_at, history_retention_days, history_paused FROM users WHERE login = ?
`

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByLogin, login)
	var i User
	err := row.Scan(
		&i.Login,
		&i.GithubID,
		&i.Name,
		&i.AvatarUrl,
		&i.TokenVersion,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.HistoryRetentionDays,
		&i.HistoryPaused,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (login, github_id, token_version) VALUES (?, ?, ?)
`

type InsertUserParams struct {
	Login        string
	GithubID     int64
	TokenVersion int64
}

// New accounts start at a random token version (see auth.NewTokenVersion).
func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser, arg.Login, arg.GithubID, arg.TokenVersion)
	return err
}

const listBookmarks = `-- name: ListBookmarks :many

SELECT login, repo, created_at, note, note_terms FROM bookmarks WHERE login = ? ORDER BY created_at DESC, rowid DESC
`

// ---------- bookmarks ----------
// rowid breaks ties between rows created in the same second.
func (q *Queries) ListBookmarks(ctx context.Context, login string) ([]Bookmark, error) {
	rows, err := q.db.QueryContext(ctx, listBookmarks, login)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bookmark{}
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(
			&i.Login,
			&i.Repo,
			&i.CreatedAt,
			&i.Note,
			&i.NoteTerms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistory = `-- name: ListHistory :many
SELECT login, kind, repo, number, title, first_viewed_at, last_viewed_at, view_count FROM history
WHERE login = ?1 AND last_viewed_at >= ?2 AND (kind = ?3 OR ?3 = '')
ORDER BY last_viewed_at DESC, kind DESC, repo DESC, number DESC
LIMIT ?4
`

type ListHistoryParams struct {
	Login    string
	Since    string
	Kind     string
	PageSize int64
}

// The first page, last viewed first. Rows last viewed before since (the
// retention) are left out even if they are not pruned yet. An empty kind lists
// both kinds; written this way SQLite still reads history_recent in order,
// while a plain "kind = ?" makes it sort part of the result in a temporary B-tree.
func (q *Queries) ListHistory(ctx context.Context, arg ListHistoryParams) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, listHistory,
		arg.Login,
		arg.Since,
		arg.Kind,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []History{}
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.Login,
			&i.Kind,
			&i.Repo,
			&i.Number,
			&i.Title,
			&i.FirstViewedAt,
			&i.LastViewedAt,
			&i.ViewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistoryAfter = `-- name: ListHistoryAfter :many
SELECT login, kind, repo, number, title, first_viewed_at, last_viewed_at, view_count FROM history
WHERE login = ?1 AND last_viewed_at >= ?2 AND (kind = ?3 OR ?3 = '')
  AND (last_viewed_at, kind, repo, number) < (?4, ?5, ?6, ?7)
ORDER BY last_viewed_at DESC, kind DESC, repo DESC, number DESC
LIMIT ?8
`

type ListHistoryAfterParams struct {
	Login         string
	Since         string
	Kind          string
	AfterViewedAt string
	AfterKind     string
	AfterRepo     string
	AfterNumber   string
	PageSize      int64
}

// The page after a cursor (the last row of the previous page). The row value
// comparison lets SQLite seek history_recent straight to the cursor. sqlc types
// all its parameters like the first column (text); SQLite still compares
// after_number as an integer (the column's affinity).
func (q *Queries) ListHistoryAfter(ctx context.Context, arg ListHistoryAfterParams) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, listHistoryAfter,
		arg.Login,
		arg.Since,
		arg.Kind,
		arg.AfterViewedAt,
		arg.AfterKind,
		arg.AfterRepo,
		arg.AfterNumber,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []History{}
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.Login,
			&i.Kind,
			&i.Repo,
			&i.Number,
			&i.Title,
			&i.FirstViewedAt,
			&i.LastViewedAt,
			&i.ViewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueueItems = `-- name: ListQueueItems :many

SELECT login, repo, number, title, added_at, last_seen_at, note, note_terms, title_terms FROM queue_items WHERE login = ? ORDER BY added_at DESC, rowid DESC
`

// ---------- review queue ----------
func (q *Queries) ListQueueItems(ctx context.Context, login string) ([]QueueItem, error) {
	rows, err := q.db.QueryContext(ctx, listQueueItems, login)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueueItem{}
	for rows.Next() {
		var i QueueItem
		if err := rows.Scan(
			&i.Login,
			&i.Repo,
			&i.Number,
			&i.Title,
			&i.AddedAt,
			&i.LastSeenAt,
			&i.Note,
			&i.NoteTerms,
			&i.TitleTerms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markQueueItemSeen = `-- name: MarkQueueItemSeen :one
UPDATE queue_items
SET last_seen_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE login = ? AND repo = ? AND number = ?
RETURNING login, repo, number, title, added_at, last_seen_at, note, note_terms, title_terms
`

type MarkQueueItemSeenParams struct {
	Login  string
	Repo   string
	Number int64
}

func (q *Queries) MarkQueueItemSeen(ctx context.Context, arg MarkQueueItemSeenParams) (QueueItem, error) {
	row := q.db.QueryRowContext(ctx, markQueueItemSeen, arg.Login, arg.Repo, arg.Number)
	var i QueueItem
	err := row.Scan(
		&i.Login,
		&i.Repo,
		&i.Number,
		&i.Title,
		&i.AddedAt,
		&i.LastSeenAt,
		&i.Note,
		&i.NoteTerms,
		&i.TitleTerms,
	)
	return i, err
}

const pruneHistory = `-- name: PruneHistory :exec
DELETE FROM history WHERE login = ?1 AND last_viewed_at < ?2
`

type PruneHistoryParams struct {
	Login  string
	Before string
}

// Deletes the rows last viewed before the retention.
func (q *Queries) PruneHistory(ctx context.Context, arg PruneHistoryParams) error {
	_, err := q.db.ExecContext(ctx, pruneHistory, arg.Login, arg.Before)
	return err
}

const recordView = `-- name: RecordView :one

INSERT INTO history (login, kind, repo, number, first_viewed_at, last_viewed_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?5)
ON CONFLICT (login, kind, repo, number) DO UPDATE SET
  repo = excluded.repo,
  last_viewed_at = excluded.last_viewed_at,
  view_count = history.view_count + 1
RETURNING login, kind, repo, number, title, first_viewed_at, last_viewed_at, view_count
`

type RecordViewParams struct {
	Login    string
	Kind     string
	Repo     string
	Number   int64
	ViewedAt string
}

// ---------- history ----------
// The Worker passes the timestamps (RFC 3339 UTC with milliseconds) instead of
// using SQLite's clock: milliseconds keep quick views in order, and the
// retention cutoffs come from the same clock, which tests can move.
// A view without a title: a new row starts with both times at viewed_at and
// view_count 1; a known one counts the view, moves last_viewed_at, keeps its
// title and takes the request's spelling of the repo.
func (q *Queries) RecordView(ctx context.Context, arg RecordViewParams) (History, error) {
	row := q.db.QueryRowContext(ctx, recordView,
		arg.Login,
		arg.Kind,
		arg.Repo,
		arg.Number,
		arg.ViewedAt,
	)
	var i History
	err := row.Scan(
		&i.Login,
		&i.Kind,
		&i.Repo,
		&i.Number,
		&i.Title,
		&i.FirstViewedAt,
		&i.LastViewedAt,
		&i.ViewCount,
	)
	return i, err
}

const recordViewWithTitle = `-- name: RecordViewWithTitle :one
INSERT INTO history (login, kind, repo, number, title, first_viewed_at, last_viewed_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?6)
ON CONFLICT (login, kind, repo, number) DO UPDATE SET
  repo = excluded.repo,
  title = excluded.title,
  last_viewed_at = excluded.last_viewed_at,
  view_count = history.view_count + 1
RETURNING login, kind, repo, number, title, first_viewed_at, last_viewed_at, view_count
`

type RecordViewWithTitleParams struct {
	Login    string
	Kind     string
	Repo     string
	Number   int64
	Title    *string
	ViewedAt string
}

// The same with a title from the request, which replaces the stored one.
func (q *Queries) RecordViewWithTitle(ctx context.Context, arg RecordViewWithTitleParams) (History, error) {
	row := q.db.QueryRowContext(ctx, recordViewWithTitle,
		arg.Login,
		arg.Kind,
		arg.Repo,
		arg.Number,
		arg.Title,
		arg.ViewedAt,
	)
	var i History
	err := row.Scan(
		&i.Login,
		&i.Kind,
		&i.Repo,
		&i.Number,
		&i.Title,
		&i.FirstViewedAt,
		&i.LastViewedAt,
		&i.ViewCount,
	)
	return i, err
}

const renameUser = `-- name: RenameUser :exec
UPDATE users SET login = ? WHERE github_id = ?
`

type RenameUserParams struct {
	Login    string
	GithubID int64
}

// Moves the account (and, through ON UPDATE CASCADE, its bookmarks, queue and
// history) to another handle.
func (q *Queries) RenameUser(ctx context.Context, arg RenameUserParams) error {
	_, err := q.db.ExecContext(ctx, renameUser, arg.Login, arg.GithubID)
	return err
}

const setHistorySettings = `-- name: SetHistorySettings :one
UPDATE users SET history_retention_days = ?, history_paused = ? WHERE github_id = ?
RETURNING login, github_id, name, avatar_url, token_version, created_at, last_login_at, history_retention_days, history_paused
`

type SetHistorySettingsParams struct {
	HistoryRetentionDays int64
	HistoryPaused        int64
	GithubID             int64
}

func (q *Queries) SetHistorySettings(ctx context.Context, arg SetHistorySettingsParams) (User, error) {
	row := q.db.QueryRowContext(ctx, setHistorySettings, arg.HistoryRetentionDays, arg.HistoryPaused, arg.GithubID)
	var i User
	err := row.Scan(
		&i.Login,
		&i.GithubID,
		&i.Name,
		&i.AvatarUrl,
		&i.TokenVersion,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.HistoryRetentionDays,
		&i.HistoryPaused,
	)
	return i, err
}

const touchUserLogin = `-- name: TouchUserLogin :one
UPDATE users
SET name = ?,
    avatar_url = ?,
    last_login_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE github_id = ?
RETURNING login, github_id, name, avatar_url, token_version, created_at, last_login_at, history_retention_days, history_paused
`

type TouchUserLoginParams struct {
	Name      *string
	AvatarUrl *string
	GithubID  int64
}

func (q *Queries) TouchUserLogin(ctx context.Context, arg TouchUserLoginParams) (User, error) {
	row := q.db.QueryRowContext(ctx, touchUserLogin, arg.Name, arg.AvatarUrl, arg.GithubID)
	var i User
	err := row.Scan(
		&i.Login,
		&i.GithubID,
		&i.Name,
		&i.AvatarUrl,
		&i.TokenVersion,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.HistoryRetentionDays,
		&i.HistoryPaused,
	)
	return i, err
}

const trimHistory = `-- name: TrimHistory :exec
DELETE FROM history WHERE rowid IN (
  SELECT h.rowid FROM history AS h WHERE h.login = ?1
  ORDER BY h.last_viewed_at DESC, h.kind DESC, h.repo DESC, h.number DESC
  LIMIT -1 OFFSET ?2
)
`

type TrimHistoryParams struct {
	Login   string
	MaxRows int64
}

// Keeps the user's max_rows most recently viewed rows and deletes the others.
func (q *Queries) TrimHistory(ctx context.Context, arg TrimHistoryParams) error {
	_, err := q.db.ExecContext(ctx, trimHistory, arg.Login, arg.MaxRows)
	return err
}

const updateQueueItem = `-- name: UpdateQueueItem :one
UPDATE queue_items SET
  title = COALESCE(?1, title),
  title_terms = COALESCE(?2, title_terms),
  note = COALESCE(?3, note),
  note_terms = COALESCE(?4, note_terms)
WHERE login = ?5 AND repo = ?6 AND number = ?7
RETURNING login, repo, number, title, added_at, last_seen_at, note, note_terms, title_terms
`

type UpdateQueueItemParams struct {
	Title      *string
	TitleTerms *string
	Note       *string
	NoteTerms  *string
	Login      string
	Repo       string
	Number     int64
}

// Like UpsertQueueItem for an item that must be queued already: it never adds back one removed meanwhile.
func (q *Queries) UpdateQueueItem(ctx context.Context, arg UpdateQueueItemParams) (QueueItem, error) {
	row := q.db.QueryRowContext(ctx, updateQueueItem,
		arg.Title,
		arg.TitleTerms,
		arg.Note,
		arg.NoteTerms,
		arg.Login,
		arg.Repo,
		arg.Number,
	)
	var i QueueItem
	err := row.Scan(
		&i.Login,
		&i.Repo,
		&i.Number,
		&i.Title,
		&i.AddedAt,
		&i.LastSeenAt,
		&i.Note,
		&i.NoteTerms,
		&i.TitleTerms,
	)
	return i, err
}

const upsertBookmark = `-- name: UpsertBookmark :one
INSERT INTO bookmarks (login, repo, note, note_terms) VALUES (?, ?, ?, ?)
ON CONFLICT (login, repo) DO UPDATE SET
  repo = excluded.repo,
  note = COALESCE(excluded.note, bookmarks.note),
  note_terms = COALESCE(excluded.note_terms, bookmarks.note_terms)
RETURNING login, repo, created_at, note, note_terms
`

type UpsertBookmarkParams struct {
	Login     string
	Repo      string
	Note      *string
	NoteTerms *string
}

// An existing row keeps its created_at; the spelling of the repo follows the request. A NULL note keeps the row's
// note, ” clears it (and reads as no note). note_terms is the note as the search indexes it (see
// migrations/0003_notes.sql).
func (q *Queries) UpsertBookmark(ctx context.Context, arg UpsertBookmarkParams) (Bookmark, error) {
	row := q.db.QueryRowContext(ctx, upsertBookmark,
		arg.Login,
		arg.Repo,
		arg.Note,
		arg.NoteTerms,
	)
	var i Bookmark
	err := row.Scan(
		&i.Login,
		&i.Repo,
		&i.CreatedAt,
		&i.Note,
		&i.NoteTerms,
	)
	return i, err
}

const upsertQueueItem = `-- name: UpsertQueueItem :one
INSERT INTO queue_items (login, repo, number, title, title_terms, note, note_terms) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (login, repo, number) DO UPDATE SET
  repo = excluded.repo,
  title = COALESCE(excluded.title, queue_items.title),
  title_terms = COALESCE(excluded.title_terms, queue_items.title_terms),
  note = COALESCE(excluded.note, queue_items.note),
  note_terms = COALESCE(excluded.note_terms, queue_items.note_terms)
RETURNING login, repo, number, title, added_at, last_seen_at, note, note_terms, title_terms
`

type UpsertQueueItemParams struct {
	Login      string
	Repo       string
	Number     int64
	Title      *string
	TitleTerms *string
	Note       *string
	NoteTerms  *string
}

// A NULL title or note keeps the row's (a bare PUT never erases them); a note of ” clears it (and reads as no
// note). *_terms are the texts as the search indexes them (see migrations/0003_notes.sql).
func (q *Queries) UpsertQueueItem(ctx context.Context, arg UpsertQueueItemParams) (QueueItem, error) {
	row := q.db.QueryRowContext(ctx, upsertQueueItem,
		arg.Login,
		arg.Repo,
		arg.Number,
		arg.Title,
		arg.TitleTerms,
		arg.Note,
		arg.NoteTerms,
	)
	var i QueueItem
	err := row.Scan(
		&i.Login,
		&i.Repo,
		&i.Number,
		&i.Title,
		&i.AddedAt,
		&i.LastSeenAt,
		&i.Note,
		&i.NoteTerms,
		&i.TitleTerms,
	)
	return i, err
}
